// core/react/src/document.tsx
import React from 'react';

export default function Document({
  body,
  head,
  pageData,
  scripts,
  stylesheets,
}: {
  body: string | null;
  head: string | null;
  pageData: unknown;
  scripts: string[];
  stylesheets: string[];
}): JSX.Element {
  let stylesheetTags = stylesheets
    .map((href) => `<link rel="stylesheet" href="${href}" type="text/css" />`)
    .join('\n');

  let headHtml = `
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
 `;
  if (head !== null) {
    headHtml += head;
  }

  headHtml += stylesheetTags;

  return (
    <html lang="en">
      <head dangerouslySetInnerHTML={{ __html: headHtml }} />
      <body>
        {body !== null ? (
          <div id="julienne-root" dangerouslySetInnerHTML={{ __html: body }} />
        ) : (
          <div id="julienne-root" />
        )}

        <script
          type="application/json"
          id="julienne-data"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(pageData) }}
        />

        {scripts.map((src) => (
          <script key={src} type="text/javascript" src={src} />
        ))}
      </body>
    </html>
  );
}

// core/svelte/src/document.svelte
<script lang="ts">
  // Svelte will render this as a normal script element if it's imported as
  // `Script`.
  import Skript from './script.svelte';

  export let body: string | undefined;
  export let head: string | undefined;
  export let pageData: any;
  // TODO: Fix this type.
  export let scripts: { [key: string]: string | number | boolean }[] = [];
  export let stylesheets: string[];
</script>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {#if head}
      {@html head}
    {/if}

    {#each stylesheets as href}
      <link rel="stylesheet" {href} type="text/css" />
    {/each}
  </head>
  <body>
    <div id="julienne-root">
      {#if body}
        {@html body}
      {/if}
    </div>

    <Skript
      type="application/json"
      id="julienne-data"
      content={JSON.stringify(pageData)} />

    {#each scripts as s}
      <Skript {...s} />
    {/each}
  </body>
</html>
