// core/svelte-render/src/document.svelte
<script lang="ts">
  export let body: string | undefined;
  export let head: string | undefined;
  export let pageData: any;
  export let scripts: string[];
  export let stylesheets: string[];

  // This is necessary so svelte-preprocess doesn't try to preprocess the data
  // script element.
  let script = 'script';

  // The julienne-data script tag must be created as a string and rendered as
  // raw html because it appears that svelte doesn't let you template the content
  // of a script element.
</script>


<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {#if head}
    {@html head}
  {/if}

  {#each stylesheets as href}
    <link rel="stylesheet" {href} type="text/css" />
  {/each}
</head>
<body>
  <div id="julienne-root">
    {#if body}
      {@html body}
    {/if}
  </div>

  {@html `<${script} type="application/json" id="julienne-data">${JSON.stringify(pageData)}</${script}>`}

  {#each scripts as src}
    <script type="text/javascript" {src}></script>
  {/each}
</body>
</html>

// core/react-render/src/document.tsx
import React from 'react';

export default function Document({
  body,
  head,
  pageData,
  scripts,
  stylesheets,
}: {
  body: string | null;
  head: string | null;
  pageData: unknown;
  scripts: string[];
  stylesheets: string[];
}): JSX.Element {
  let stylesheetTags = stylesheets.map(
    (href) => `<link rel="stylesheet" href="${href}" type="text/css" />`,
  );

  let headHtml = `
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
 `;
  if (head !== null) {
    headHtml += head;
  }

  headHtml += stylesheetTags;

  return (
    <html lang="en">
      <head dangerouslySetInnerHTML={{ __html: headHtml }} />
      <body>
        {body !== null ? (
          <div id="julienne-root" dangerouslySetInnerHTML={{ __html: body }} />
        ) : (
          <div id="julienne-root" />
        )}

        <script
          type="application/json"
          id="julienne-data"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(pageData) }}
        />

        {scripts.map((src) => (
          <script key={src} type="text/javascript" src={src} />
        ))}
      </body>
    </html>
  );
}
