// examples/react/src/components/counter.tsx
import React, { useEffect, useState } from 'react';
import cc from 'classcat';

import * as styles from './counter.module.css';

export default function Button(): JSX.Element {
  let [count, setCount] = useState(0);
  let isEven = count % 2 === 0;

  useEffect(() => {
    let interval = setInterval(() => {
      setCount((c) => c + 1);
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  let cls = cc([styles.root, isEven ? styles.even : styles.odd]);

  return <div className={cls}>{count}</div>;
}

// examples/svelte/src/components/counter.svelte
<script>
  import { onMount } from 'svelte';

  let count = 0;

  $: isEven = count % 2 === 0;

  onMount(() => {
    let interval = setInterval(() => {
      count += 1;
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  });
</script>

<div class:even={isEven} class:odd={!isEven}>
  {count}
</div>

<style>
  div {
    font-family: 'Open Sans';
  }

  .even {
    color: goldenrod;
  }

  .odd {
    color: dimgray;
  }
</style>
